# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
repos:
  CRAN: https://cloud.r-project.org
  PIK:  https://rse.pik-potsdam.de/r/packages/
cache: packages
latex: false
pandoc: false
sudo: false
r_packages:
  - covr
  - devtools
  - testthat
  - lucode
script:
  - Rscript -e 'testthat::test_dir("tests/testthat/",stop_on_failure = TRUE,stop_on_warning = TRUE)'
after_success:
  - Rscript -e 'covr::codecov()'
